#!/bin/sh

set -o errexit
set -o nounset

function expect() {
	(
		cd ${1} || exit ${LINENO}
		[ -x examples.sh ] || exit ${LINENO}
		[ -f expect.txt ] || exit ${LINENO}

		diff <(./examples.sh) expect.txt
	)
}

export RENDERIZER_TESTING=true

for t in issues/*/examples.sh ../examples/*/examples.sh; do
	expect $(dirname ${t})
done

echo success
