project_name: renderizer
builds:
  - 
    binary: renderizer
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: '-s -w -X main.version={{.Version}} -X main.tag={{.Tag}} -X main.commit={{.Commit}} -X main.date={{ time "20060102" }}'

dist: release/dist

release:
  github:
    owner: gomatic
    name: renderizer

sign:
  artifacts: all

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - docs
      - Merge pull request
      - Merge branch

archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
